---
abstract: 'Get function list from package.'
author:
  - 'Tokuhiro Matsuno <tokuhirom AAJKLFJEF@ GMAIL COM>'
build_requires:
  Test::More: 0.98
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.4.3, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Module-Functions
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
provides:
  Module::Functions:
    file: lib/Module/Functions.pm
    version: v2.1.3
requires:
  Exporter: 0
  Sub::Identify: 0.04
  parent: 0
  perl: 5.008005
resources:
  bugtracker: https://github.com/tokuhirom/Module-Functions/issues
  homepage: https://github.com/tokuhirom/Module-Functions
  repository: git://github.com/tokuhirom/Module-Functions.git
version: 2.1.3
x_contributors:
  - 'bayashi <bayashi@cpan.org>'
  - 'Kazuhiro Osawa <yappo@shibuya.pl>'
  - 'tokuhirom <tokuhirom@gmail.com>'
